version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-ecommerce
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-ecommerce
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
