spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 1000
        enable.idempotence: true
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

  cache:
    redis:
      time-to-live: 7200000

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: WARN
    net.engineeringdigest.ecommerce: INFO
  file:
    max-size: 100MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
